---
- hosts: all
  become: true
  tasks: 
    - name: installing services
      apt: 
        name:
          - apache
          - php
    - name: ensure apache starts
      service: name=apache state=started enable=yes    
